services:
  postgis-source:
    image: postgis/postgis:16-3.4
    container_name: postgis-source
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./postgis-data:/var/lib/postgresql/data/
    networks:
      - geopnetw

  minio-target:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio-target
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio-data:/data
    networks:
      - geopnetw

  dagster_app:
    restart: unless-stopped
    container_name: dagster_app
    build:
      context: .
      dockerfile: ./Dockerfile_Dagster
    ports:
      - "3000:3000"
    volumes:
      - ./dagster_app:/opt/dagster/app
      - ./dagster_home:/opt/dagster/dagster_home
    env_file:
      - ./.env
    depends_on:
      - postgis-source
      - minio-target
    networks:
      - geopnetw

networks:
  geopnetw:
    name: geopnetw
    driver: bridge
